---
title: "Topics & aims"
---
<br>

## Global change

**Adaptation and acclimation to global change**

My research is motivated by the goal of improving predictions of biodiversity's adaptation to global change. Like the field of global change biology, this work is highly integrative and spans experimental biology, physiology, and genome biology. I characterize organismal responses to global change stressors, evaluate fitness benefits these physiological responses, and interrogate their regulatory and genomic basis. This information is critical for identifying traits that promote resistance and resilience to global change, their mechanistic basis, and how they may evolve.

<u>Example:</u> **Bogan SN**, Johnson KM, and Hofmann GE. 2020. [Changes in Genome-wide Methylation and Gene Expression in Response to Future *p*CO2 Extremes in the Antarctic Pteropod *Limacina helicina antarctica*](https://www.frontiersin.org/journals/marine-science/articles/10.3389/fmars.2019.00788/full). *Frontiers in Marine Science* 6: 788.

<br>

## Genome biology 

**Genomic constraints on environmental adaptation**

Environmental adaptation can be constrained or facilitated by the structure and diversity of genomes. For example, chromosomal inversions can yield phenotypic effects of great fitness cost or benefit in a given environment. Repetitive genomic regions can facilitate copy number variation and subsequent selection on copy number in environments where more or fewer copies are beneficial. My research in evolutionary genomics seeks to understand how environmental adaptation is constrained or limited by these processes.  

<u>Example:</u> **Bogan SN**, Surendran N, Hotaling S, *et al.* and Kelley JL. 2024. [Temperature and Pressure Shaped the Evolution of Antifreeze Proteins in Polar and Deep Sea Zoarcoid Fishes](https://www.biorxiv.org/content/10.1101/2024.08.24.609455v1). *bioRxiv* (in revision)

<br>

## Epigenetics

**Epigenetics of phenotypic plasticity and acclimation**

Epigenetic modifications to DNA and chromatin and hypothesized to underpin plastic responses to environmental change by affecting gene expression and subsequent phenotypes. I have studied and reviewed complex associations between DNA methylation, chromatin accessibility, and gene expression associated with transgenerational and developmental plasticity. 

<u>Examples:</u> *Bogan SN*, Strader ME, and Hofmann GE. 2023. [Associations between DNA Methylation and Gene Expression Depend on Chromatin Accessibility during Transgenerational Plasticity](https://bmcbiol.biomedcentral.com/articles/10.1186/s12915-023-01645-8). *BMC Biology* 21: 149.  

*Bogan SN* and Yi SV. 2024. [Potential Role of DNA Methylation in Plastic Responses to the Environment across Cells, Organisms, and Populations](https://academic.oup.com/gbe/article/16/2/evae022/7602727). *Genome Biology and Evolution* 16: evae022.

<br>

## Phenotypic plasticity

**Evolutionary biology of phenotypic plasticity**

Phenotypic plasticity can both evolve by - and affect - natural selection. However, evolutionary biology maintains a poor ability to predict when plasticity or environmental acclimation is adaptive. Furthermore, direct evidence of plasticity's role in modifying selection on phenotypes is largely indirect. I am investigating the ecological and evolutionary processes that shape the fitness effects of plasticity and acclimation in addition to developing directly testable theory and evolutionary genetic models for plasticity's role in evolution.

<u>Example:</u> *Bogan SN*, Porat OI, Meneses M, and Hofmann GE. 2024. [Thermal Plasticity Has Greater Fitness Costs among Thermally Tolerant Genotypes of *Tigriopus californicus*](https://besjournals.onlinelibrary.wiley.com/doi/10.1111/1365-2435.14568). *Functional Ecology* 38: 1562–1577.  

