---
title: "News & updates"
---
<div align="center">
**2026**
</div>

Jan 23rd, 2026 - This summer, I'll be starting at Skidmore College as an Assistant Professor in the Department of Biology! I'm looking forward to developing research and teaching on the genomics of environmental adaptation and acclimation in my home state of New York.

<br>

<div align="center">
**2025**
</div>

Dec 16th, 2025 - New preprint led by Tina Cai! We performed reduced-representation bisulfite sequencing on gill and foot tissue of California mussels transplanted between intertidal microhabitats. Tissues showed significantly different epigenetic responses to *in situ* conditions.  [Available on bioRxiv](https://www.biorxiv.org/content/10.64898/2025.12.12.693252v1.abstract).

<br>

Oct 30th, 2025 - Owen Moosman's lead author paper is [out in *Heredity*](https://www.nature.com/articles/s41437-025-00803-8)! We observed abundant haplotype diversity in the copy number of antifreeze protein genes across Zoarcoidei fishes.

<br>

Sept 11th, 2025 - Our paper on the evolution of antifreeze protein genes in Zoarcoidei fishes is [out in *Molecular Biology and Evolution*](https://academic.oup.com/mbe/article/42/10/msaf219/8251091)! We show that copy number of antifreeze protein genes increased in polar and shallow-water species. Furthermore, translocation-duplication shaped associations between environment and copy number.

<br>

May 26th, 2025 - In collaboration with the Resources for Inclusive Eduction in Evolution (RIE2) Working Group, colleagues and I have published an open-source teaching module and lesson plan for lecturing on the evolutionary biology of phenotypic plasticity. Find our [module here on QUBES](https://qubeshub.org/publications/5396/about/3) along with [RIE2's other modules](https://qubeshub.org/community/groups/rie2/teaching_modules).

